import Project.ConnectionProvider;
import java.awt.Color;
import static java.lang.Character.isDigit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.swing.JOptionPane;
import java.time.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shaun
 */
public class AddAdmin extends javax.swing.JFrame {

    /**
     * Creates new form AddAdmin
     */
    public AddAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newNewspaperHeadingLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        saveButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        productIDLabel = new javax.swing.JLabel();
        adminNoLabel = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        nameLabel = new javax.swing.JLabel();
        adminPasswordTextField = new javax.swing.JTextField();
        sundayRateLabel = new javax.swing.JLabel();
        adminNameTextField = new javax.swing.JTextField();
        weekdayRateLabel = new javax.swing.JLabel();
        adminUsernameTextField = new javax.swing.JTextField();
        adminContactNoTextField = new javax.swing.JTextField();
        descriptionLabel = new javax.swing.JLabel();
        activateLabel = new javax.swing.JLabel();
        adminEmailTextField = new javax.swing.JTextField();
        activateLabel1 = new javax.swing.JLabel();
        isSuperadminComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(290, 220));
        setMaximumSize(new java.awt.Dimension(995, 540));
        setMinimumSize(new java.awt.Dimension(995, 540));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(995, 540));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newNewspaperHeadingLabel.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        newNewspaperHeadingLabel.setText("Add Admin");
        getContentPane().add(newNewspaperHeadingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 910, 20));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 940, 10));

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save_icon.png"))); // NOI18N
        saveButton.setText("  Save");
        saveButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                saveButtonComponentShown(evt);
            }
        });
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 150, 50));

        resetButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset_icon.png"))); // NOI18N
        resetButton.setText("  Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, 140, 50));

        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel_icon.png"))); // NOI18N
        cancelButton.setText("  Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, 140, 50));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 910, 10));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 940, 10));

        productIDLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        productIDLabel.setText("Admin No.");
        getContentPane().add(productIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        adminNoLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        adminNoLabel.setForeground(new java.awt.Color(255, 51, 0));
        adminNoLabel.setText("21");
        getContentPane().add(adminNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 142, -1, 30));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 910, 20));

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameLabel.setText("Admin Name");
        getContentPane().add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        adminPasswordTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminPasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPasswordTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(adminPasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 240, -1));

        sundayRateLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sundayRateLabel.setText("Password");
        getContentPane().add(sundayRateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        adminNameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(adminNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 240, -1));

        weekdayRateLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        weekdayRateLabel.setText("Username");
        getContentPane().add(weekdayRateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        adminUsernameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminUsernameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(adminUsernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 240, -1));

        adminContactNoTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminContactNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminContactNoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(adminContactNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 240, -1));

        descriptionLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        descriptionLabel.setText("Email");
        getContentPane().add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, -1));

        activateLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        activateLabel.setText("Contact No.");
        getContentPane().add(activateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, -1));

        adminEmailTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminEmailTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(adminEmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 240, -1));

        activateLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        activateLabel1.setText("Is SuperAdmin");
        getContentPane().add(activateLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, -1, -1));

        isSuperadminComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        isSuperadminComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));
        getContentPane().add(isSuperadminComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 360, 220, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_admin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_saveButtonComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonComponentShown

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:

        String adminNo = adminNoLabel.getText();
        String adminName = adminNameTextField.getText();
        String adminUsername = adminUsernameTextField.getText();
        String adminPasword = adminPasswordTextField.getText();
        String adminContactNo = adminContactNoTextField.getText();
        String adminEmail = adminEmailTextField.getText();
        String isSuperadmin = (String)isSuperadminComboBox.getSelectedItem();

        try
        {
            //Check if all fields are filled
            if(adminName.equals("") || adminUsername.equals("") || adminPasword.equals(""))
            {
                throw new NullFieldException();
            }

            //Check if contact number has 10 values 
            if(adminContactNo.length() != 10)
            {
                throw new ContactNumberException();
            }
            
            //Check if contact number is in digits 
            for(int i=0; i < adminContactNo.length(); i++)
            {
                if(!(isDigit(adminContactNo.charAt(i))))
                {
                    throw new ContactNumberException();
                }
            }
            
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs;
            
            //Check for duplicate usernames
            rs = st.executeQuery(("select admin_username from Admin"));
            while(rs.next())
            {
                if(rs.getString(1).equals(adminUsername))
                {
                    throw new SQLIntegrityConstraintViolationException();
                }
            }
  
            //If a super admin is created then show a warning confirmation box
            //int confirm=100;
            if(isSuperadmin.equals("Yes"))
            {
                 int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to create a new SuperAdmin.", "Confirmation", JOptionPane.YES_NO_OPTION);
                 if(confirm == JOptionPane.NO_OPTION)
                 {
                     throw new StopProcessException();
                 }
            }
            //ADD YES TO SUPERADMIN COLUMN
            st.executeUpdate("insert into Admin values ('"+adminNo+"','"+adminName+"','"+adminUsername+"','"+adminPasword+"','"+adminContactNo+"','"+adminEmail+"','"+isSuperadmin+"')");

            JOptionPane.showMessageDialog(null, "Successfully Added a new Admin");
            setVisible(false);
            new AddAdmin().setVisible(true);

        }

        //Fields are null
        catch(NullFieldException e)
        {
            //new NullFieldException();
            JOptionPane.showMessageDialog(null,"Please fill all the details");
        }
        
        //Contact number is not right
        catch(ContactNumberException e)
        {
            JOptionPane.showMessageDialog(null,"Please enter a valid Contact Number");
        }
        
        //Duplicate username
        catch (SQLIntegrityConstraintViolationException e)
        {
            JOptionPane.showMessageDialog(null, "This usename is alerady taken");
        }
        
        //Stop Process and DO NOTHING
        catch(StopProcessException e){}

        //Any other Exceotion
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
            System.out.println(e);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AddAdmin().setVisible(true);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        //System.exit(0);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void adminPasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminPasswordTextFieldActionPerformed

    private void adminNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminNameTextFieldActionPerformed

    private void adminUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminUsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminUsernameTextFieldActionPerformed

    private void adminContactNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminContactNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminContactNoTextFieldActionPerformed

    private void adminEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminEmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminEmailTextFieldActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try
        {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            
            ResultSet rs = st.executeQuery("select max(admin_no) from Admin");
            if(rs.next())  //first as it would be possible there is not value present
            {
                int news_id = rs.getInt(1);
                news_id = news_id + 1;
                
                String str = String.valueOf(news_id);
                adminNoLabel.setText(str);
            }
            else
            {
                System.out.println("HERE ELSE");
                adminNoLabel.setText("1");
            }
        }
        catch(Exception e)
        {
            System.out.println("HERE");
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activateLabel;
    private javax.swing.JLabel activateLabel1;
    private javax.swing.JTextField adminContactNoTextField;
    private javax.swing.JTextField adminEmailTextField;
    private javax.swing.JTextField adminNameTextField;
    private javax.swing.JLabel adminNoLabel;
    private javax.swing.JTextField adminPasswordTextField;
    private javax.swing.JTextField adminUsernameTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JComboBox<String> isSuperadminComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel newNewspaperHeadingLabel;
    private javax.swing.JLabel productIDLabel;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel sundayRateLabel;
    private javax.swing.JLabel weekdayRateLabel;
    // End of variables declaration//GEN-END:variables

    static class StopProcessException extends Exception{}
    static class NullFieldException extends Exception{}
    static class ContactNumberException extends Exception{}
    
}
