import javax.swing.*;
import java.sql.*;
import Project.ConnectionProvider;
import java.text.SimpleDateFormat;
import net.proteanit.sql.DbUtils;
/*

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shaun
 */
//User defined Exception

class DuplicateEntryException extends Exception{}

public class AddSubscription extends javax.swing.JFrame {

    /**
     * Creates new form AddSubscription
     */
    public AddSubscription() {
        initComponents();
        
        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date date = new java.util.Date();
        subscriptionDateTextField.setText(dFormat.format(date));
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        productIDLabel = new javax.swing.JLabel();
        subscriptionIDLabel = new javax.swing.JLabel();
        contactNumberLabel = new javax.swing.JLabel();
        contactNumberTextField = new javax.swing.JTextField();
        newspaperIDLabel = new javax.swing.JLabel();
        newspaperIDTextField = new javax.swing.JTextField();
        subscriptionDateLabel = new javax.swing.JLabel();
        subscriptionDateTextField = new javax.swing.JTextField();
        newspaperNameLabel = new javax.swing.JLabel();
        newspaperNameTextField = new javax.swing.JTextField();
        customerNameLabel = new javax.swing.JLabel();
        customerNameTextField = new javax.swing.JTextField();
        confrimButton = new javax.swing.JButton();
        noteLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 190));
        setMaximumSize(new java.awt.Dimension(750, 560));
        setMinimumSize(new java.awt.Dimension(750, 560));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(750, 560));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Add Subsctiption");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save_icon.png"))); // NOI18N
        saveButton.setText("  Save");
        saveButton.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                saveButtonComponentShown(evt);
            }
        });
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 130, 50));

        resetButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset_icon.png"))); // NOI18N
        resetButton.setText("  Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 130, 50));

        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel_icon.png"))); // NOI18N
        cancelButton.setText("  Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 120, 50));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 700, 10));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 710, 20));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 700, 20));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 700, 10));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 710, 20));

        productIDLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        productIDLabel.setText("Subscription ID");
        getContentPane().add(productIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        subscriptionIDLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        subscriptionIDLabel.setForeground(new java.awt.Color(255, 51, 0));
        subscriptionIDLabel.setText("21");
        getContentPane().add(subscriptionIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, 40));

        contactNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactNumberLabel.setText("Customer Contact No");
        getContentPane().add(contactNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        contactNumberTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        contactNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumberTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(contactNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 250, -1));

        newspaperIDLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newspaperIDLabel.setText("Newspaper ID");
        getContentPane().add(newspaperIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        newspaperIDTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newspaperIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newspaperIDTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(newspaperIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 250, -1));

        subscriptionDateLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subscriptionDateLabel.setText("Subscription Date ");
        getContentPane().add(subscriptionDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        subscriptionDateTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subscriptionDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subscriptionDateTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(subscriptionDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 250, -1));

        newspaperNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        newspaperNameLabel.setText("Newspaper Name");
        getContentPane().add(newspaperNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        newspaperNameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newspaperNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newspaperNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(newspaperNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 250, -1));

        customerNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customerNameLabel.setText("Customer Name");
        getContentPane().add(customerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        customerNameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        customerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(customerNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 250, -1));

        confrimButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        confrimButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search_icon.png"))); // NOI18N
        confrimButton.setText("  Find");
        confrimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confrimButtonActionPerformed(evt);
            }
        });
        getContentPane().add(confrimButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 120, 50));

        noteLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        noteLabel.setText("Only Enter Customer Contact No. and Newspaper ID");
        getContentPane().add(noteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_saveButtonComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonComponentShown

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:

        String subscriptionID = subscriptionIDLabel.getText();
        String custContactNo = contactNumberTextField.getText();
        String newspaperID = newspaperIDTextField.getText();
        String custName = customerNameTextField.getText();
        String newspaperName = newspaperNameTextField.getText();
        String subscriptionDate = subscriptionDateTextField.getText();
        String billStartDate = subscriptionDate;
        String subscriptionStatus = "Active";

        try
        {
            //Check if all fields are filled
            if(custContactNo.equals("") || newspaperID.equals("") || newspaperName.equals("") || custName.equals(""))
            {
                throw new NullFieldException();
            }

            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            
            ResultSet rs = st.executeQuery("select cust_contact_no,news_id,subscription_status from Customer_Newspaper where cust_contact_no='"+custContactNo+"' and news_id='"+newspaperID+"' " );
            
        
            
            while(rs.next())
            {
                String getCustContactNo = rs.getString(1);
                String getNewspaperID = rs.getString(2);
                String subscriptionStatusFetch = rs.getString(3);
                System.out.println(getCustContactNo+" "+getNewspaperID);
                if(custContactNo.equals(getCustContactNo) && newspaperID.equals(getNewspaperID))
                {
                    if(subscriptionStatusFetch.equals("Inactive"))
                    {
                        
                        throw new DuplicateEntryInactiveSubscriptionException();
                    }
                    else
                    {
                        customerNameTextField.setText("");
                        newspaperNameTextField.setText("");

                        throw new DuplicateEntryException();
                        //break;
                    }
                }
            }
            
            Date subscriptionEndDate = null;
            String billPending = "Yes";
            st.executeUpdate("insert into Customer_Newspaper values ('"+subscriptionID+"','"+custContactNo+"','"+custName+"','"+newspaperID+"','"+newspaperName+"','"+subscriptionDate+"','"+billStartDate+"',null,'"+subscriptionStatus+"','"+billPending+"',due_amount='null')");
            //String query = "insert into Customer "+"values ("

            JOptionPane.showMessageDialog(null, "Successfully Added Subscription Details");
            setVisible(false);
            new AddSubscription().setVisible(true);

        }

        //Fields are null
        catch(NullFieldException e)
        {
            //new NullFieldException();
            JOptionPane.showMessageDialog(null,"Please fill all the details");
        }
        
        //Duplicate entries
        catch(DuplicateEntryException e)
        {
            JOptionPane.showMessageDialog(null, "This Subscription already Exists");
        }
        
        //Duplicate entries but Subscription is Inactive
        catch(DuplicateEntryInactiveSubscriptionException e)
        {
            JOptionPane.showMessageDialog(null, "This Subscription Already Exists but it is Inactive. Please use 'Update Subscription' Menu to ReActivate this Subscription");
        }

        //Any other Exceotion
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
            System.out.println(e);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AddSubscription().setVisible(true);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        //System.exit(0);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void contactNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberTextFieldActionPerformed

    private void newspaperIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newspaperIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newspaperIDTextFieldActionPerformed

    private void subscriptionDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subscriptionDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subscriptionDateTextFieldActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        
                
        try
        {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            
            ResultSet rs = st.executeQuery("select max(subscription_id) from Customer_Newspaper");
            if(rs.next())  //first as it would be possible there is not value present
            {
                int news_id = rs.getInt(1);
                news_id = news_id + 1;
                
                String str = String.valueOf(news_id);
                subscriptionIDLabel.setText(str);
            }
            else
            {
                System.out.println("HERE ELSE");
                subscriptionIDLabel.setText("1");
            }
        
        }
        catch(Exception e)
        {
            System.out.println("HERE");
            JOptionPane.showMessageDialog(null, e);
        }
        
        customerNameTextField.setEditable(false);
        newspaperNameTextField.setEditable(false);
        subscriptionDateTextField.setEditable(false);
        
    }//GEN-LAST:event_formComponentShown

    private void newspaperNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newspaperNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newspaperNameTextFieldActionPerformed

    private void customerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameTextFieldActionPerformed

    private void confrimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confrimButtonActionPerformed
        // TODO add your handling code here:
       
        String custContactNo = contactNumberTextField.getText();
        String newspaperID = newspaperIDTextField.getText();
        
        try
        {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            
            //For customer name****************
            ResultSet rs = st.executeQuery("select cust_name from Customer where cust_contact_no ='"+custContactNo+"'");
            if(rs.next())  //first as it would be possible there is not value present
            {
                String custName = rs.getString(1);
                customerNameTextField.setText(custName);
            }
            else
            {
                System.out.println("HERE ELSE");
                customerNameTextField.setText("");
            }
            
            //For newspaper name********************
            rs = st.executeQuery("select news_name from Newspaper where news_id ='"+newspaperID+"'");
            if(rs.next())  //first as it would be possible there is not value present
            {
                String newspaperName = rs.getString(1);
                newspaperNameTextField.setText(newspaperName);
            }
            else
            {
                System.out.println("HERE ELSE");
                newspaperNameTextField.setText("");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_confrimButtonActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
        //setVisible(false);
        //dispose();
    }//GEN-LAST:event_formWindowLostFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSubscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSubscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSubscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSubscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSubscription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confrimButton;
    private javax.swing.JLabel contactNumberLabel;
    private javax.swing.JTextField contactNumberTextField;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel newspaperIDLabel;
    private javax.swing.JTextField newspaperIDTextField;
    private javax.swing.JLabel newspaperNameLabel;
    private javax.swing.JTextField newspaperNameTextField;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JLabel productIDLabel;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel subscriptionDateLabel;
    private javax.swing.JTextField subscriptionDateTextField;
    private javax.swing.JLabel subscriptionIDLabel;
    // End of variables declaration//GEN-END:variables

    class DuplicateEntryInactiveSubscriptionException extends Exception {}
    
}
