
import Project.ConnectionProvider;
import static java.lang.Character.isDigit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.swing.JOptionPane;
import java.time.*;

import DateCallculator.CalculateDays;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Toolkit;
import java.io.FileOutputStream;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shaun
 */
//User Defined Exceptions
class DontGenerateBillException extends Exception {}

public class Billing extends javax.swing.JFrame {

    /**
     * Creates new form Billing
     */
    public Billing() {
        initComponents();
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("billingICON.png")));
        
        SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        dateLabel.setText(dFormat.format(date));
        
        //dateOfBillingTextField.setText(dFormat.format(date));
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        timeLabel.setText(dtf.format(now));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        contactNumberTextField = new javax.swing.JTextField();
        totalDueAmountTextField = new javax.swing.JTextField();
        confirmButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        custNameTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        custEmailTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        custAddressTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        custGenderTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        billDetailsTable = new javax.swing.JTable();
        generateBillButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        totalAmountTextField = new javax.swing.JTextField();
        subTotalAmountTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 190));
        setMaximumSize(new java.awt.Dimension(1119, 562));
        setMinimumSize(new java.awt.Dimension(1119, 562));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1119, 600));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billing_icon.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("Billing");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Date :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, -1, -1));

        dateLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dateLabel.setText("display date");
        getContentPane().add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Time :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 50, -1, -1));

        timeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        timeLabel.setText("display time");
        getContentPane().add(timeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Customer Contact No");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, 20));

        contactNumberTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        contactNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNumberTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(contactNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 200, -1));

        totalDueAmountTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalDueAmountTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                totalDueAmountTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                totalDueAmountTextFieldFocusLost(evt);
            }
        });
        totalDueAmountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalDueAmountTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(totalDueAmountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 170, 200, -1));

        confirmButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirmButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/confirm_icon.png"))); // NOI18N
        confirmButton.setText(" Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 130, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Total Amount to be paid       Rs.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Customer Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, 20));

        custNameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        custNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                custNameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                custNameTextFieldFocusLost(evt);
            }
        });
        custNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(custNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 260, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Customer Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, 20));

        custEmailTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        custEmailTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                custEmailTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                custEmailTextFieldFocusLost(evt);
            }
        });
        custEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custEmailTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(custEmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 260, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Customer Address");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, 20));

        custAddressTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        custAddressTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                custAddressTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                custAddressTextFieldFocusLost(evt);
            }
        });
        custAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custAddressTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(custAddressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 260, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Customer Gender");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, 20));

        custGenderTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        custGenderTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                custGenderTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                custGenderTextFieldFocusLost(evt);
            }
        });
        custGenderTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custGenderTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(custGenderTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 260, -1));

        billDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr No.", "Newspaper Name", "Weekly Rate in Rs.", "Sunday Rate in Rs.", "Bill Start Date", "Bill End Date", "Amount in Rs."
            }
        ));
        billDetailsTable.setToolTipText("");
        jScrollPane1.setViewportView(billDetailsTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 1070, 210));

        generateBillButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        generateBillButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/generate_bill_icon.png"))); // NOI18N
        generateBillButton.setText("Generate bill");
        generateBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateBillButtonActionPerformed(evt);
            }
        });
        getContentPane().add(generateBillButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 150, 40));

        resetButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset_icon.png"))); // NOI18N
        resetButton.setText(" Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 120, 40));

        closeButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel_icon.png"))); // NOI18N
        closeButton.setText(" Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 310, 120, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Due Amount        Rs.");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, -1, -1));

        totalAmountTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalAmountTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                totalAmountTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                totalAmountTextFieldFocusLost(evt);
            }
        });
        totalAmountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalAmountTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(totalAmountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, 200, -1));

        subTotalAmountTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subTotalAmountTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                subTotalAmountTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                subTotalAmountTextFieldFocusLost(evt);
            }
        });
        subTotalAmountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subTotalAmountTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(subTotalAmountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, 200, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Sub Total Amount       Rs.");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 480, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 480, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 760, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNumberTextFieldActionPerformed

    private void totalDueAmountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalDueAmountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalDueAmountTextFieldActionPerformed
     
    public int totalAmount[] = new int[50];
    
    
    String subscriptionID[] = new String[100];
    String newsID = "";
    int sundays = 0;
    int weekDays = 0;
    int newsWeeklyRate = 0;
    int newsSundayRate = 0;
    String billStartDate = "";
    String dateOfBilling = "";
    String newspaperName[] = new String[50];
    String newspaperID[] = new String[50];

    Date dateOfBillingDate = new Date();
    Date subscriptionDate = null;
    int subscriptionCount = 0;
    
    int totalDueAmount=0;
    
    
    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        
        //billDetailsTable.setModel(new DefaultTableModel());
        
        String cust_contactNo = contactNumberTextField.getText();
       
    
        try
        {
           Connection con = ConnectionProvider.getCon();
           Statement st = con.createStatement();
           
           ResultSet rs;
           
         
           //Fetch Customer details
           rs = st.executeQuery("select * from customer where cust_contact_no='"+cust_contactNo+"'");
           
           if(rs.next())
           {
               //Search and get all the details from customer table then put them on the text fields
               custNameTextField.setText(rs.getString(1));
               custEmailTextField.setText(rs.getString(3));
               custAddressTextField.setText(rs.getString(4));
               custGenderTextField.setText(rs.getString(5));
               
               custNameTextField.setEditable(false);
               custEmailTextField.setEditable(false);
               custAddressTextField.setEditable(false);
               custGenderTextField.setEditable(false);
            
               //Set editables to false
               contactNumberTextField.setEditable(false);
               confirmButton.setEnabled(false);
           }
           else
           {
               JOptionPane.showMessageDialog(null, "Contact No. does not exist");
           }
           
           
           //Find number of subscriptions for the customer and newspaper details
           rs = st.executeQuery("select news_id,news_name from customer_newspaper where cust_contact_no='"+cust_contactNo+"'");
           int index=0;
           while(rs.next())
           {
               newspaperID[index] = rs.getString(1);
               newspaperName[index] = rs.getString(2);
               
               subscriptionCount++; //number of subscriptions
               index++;
           }
           
          
           for (int i=0; i<subscriptionCount; i++)
           {
                System.out.println("\n\n For newspaperID : "+newspaperID[i]+" and Newsapaper Name : "+newspaperName[i]+"\n ");
            
               
                //Get subscription ID
                rs = st.executeQuery("select subscription_id, subscription_date from customer_newspaper where cust_contact_no='"+cust_contactNo+"' and news_id='"+newspaperID[i]+"'");
                if(rs.next())
                {
                    subscriptionID[i] = rs.getString(1);
                    subscriptionDate = rs.getDate(2);
                }
                
                //Check if subscription is active and if bill making is required
                rs = st.executeQuery("select bill_pending from customer_newspaper where subscription_id='"+subscriptionID[i]+"'");
                if(rs.next())
                {
                    if(rs.getString(1).equals("No"))
                    {
                        System.out.println("YESS");
                     continue;
                    }
                }
                
                
                //Calculate dates and days ********************
                rs = st.executeQuery("select bill_start_date,subscription_status,subscription_end_date from customer_newspaper where cust_contact_no='"+cust_contactNo+"' and news_id='"+newspaperID[i]+"'");
                if(rs.next())
                {
                    SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");

                    Date billStartDateD = rs.getDate(1);
                    dFormat.format(billStartDateD);
                    //Assign to string
                    billStartDate = dFormat.format(billStartDateD);
                    
                    
                    if(rs.getString(2).equals("Active"))
                    {
                        //Date currentDate = new Date();
                        dateOfBillingDate = new Date();
                        dFormat.format(dateOfBillingDate);
                        //Assign to string
                        dateOfBilling = dFormat.format(dateOfBillingDate);
                        System.out.println("BILL START : "+billStartDateD);
                        System.out.println("END OF SUB : "+dateOfBillingDate);
                    }
                    //If subscription is inactive but bill remains then check for time between last bill date and subscriptoin cancel date
                    else if(rs.getString(2).equals("Inactive"))
                    {
                        dateOfBillingDate = rs.getDate(3);
                        dFormat.format(dateOfBillingDate);
                        dateOfBilling = dFormat.format(dateOfBillingDate);
                        System.out.println("BILL START : "+billStartDateD);
                        System.out.println("END OF SUB : "+dateOfBillingDate);
                    }

                    
                    /*
                    //Check if bill needs to be calculated
                    if(billStartDate.equals(dateOfBilling))
                    {
                        //throw new DontGenerateBillException();
                        continue;
                    }*/
                            
                    //System.out.println(billStartDate);
                    //System.out.println(billEndDate);

                    //String [] dateParts = billStartDateD.split("-");
                    //int startDateYear = dateParts, endDateYear;
                    //int startDateMonth, endDateMonth;

                    /*int startDateDays = Integer.parseInt(billStartDate.substring(0,2));
                    int startDateMonths = Integer.parseInt(billStartDate.substring(3,5));
                    int startDateYear = Integer.parseInt(billStartDate.substring(6,10));

                    int endDateDays = Integer.parseInt(billEndDate.substring(0,2));
                    int endDateMonths = Integer.parseInt(billEndDate.substring(3,5));
                    int endDateYear = Integer.parseInt(billEndDate.substring(6,10));

                    /*
                    System.out.println(startDateDays);
                    System.out.println(startDateMonths);
                    System.out.println(startDateYear);
                    */

                    /*
                    The function CalculateDays will calculate days from start date to end_date with inclusive of start and end dats
                    But when new bill start date is assigned, next time when bill is genereated we don't need to include the start date.
                    */
                    /*
                    boolean firstTimeBill = false;
                    if(billStartDateD.equals(subscriptionDate))
                    {
                        firstTimeBill = true;
                    }*/
                    System.out.println(billStartDateD);
                    System.out.println(dateOfBillingDate);
                    //System.exit(0);
                    
                    CalculateDays cd = new CalculateDays();
                    weekDays = cd.getWorkingDaysBetweenTwoDates(billStartDateD, dateOfBillingDate, true);
                    sundays = cd.getSundaysBetweenTwoDates(billStartDateD, dateOfBillingDate, true);   

                    System.out.println("NUMBER OF WEEKDAYS - "+weekDays);
                    System.out.println("NUMBER OF SUNDAYS - "+sundays);


                }

                //Get news_ID of the newspaper that customer has subscribed to
                rs = st.executeQuery("select news_id from customer_newspaper where cust_contact_no = '"+cust_contactNo+"' and news_id = '"+newspaperID[i]+"'");       
                if(rs.next())
                {
                    newsID = rs.getString(1);
                }
                //System.out.println(newsID);

                //Fetch the rate for weekdays and sundays
                rs = st.executeQuery("select news_weekday_rate,news_sunday_rate from newspaper where news_id = '"+newsID+"'");
                if(rs.next())
                {
                    newsWeeklyRate = rs.getInt(1);
                    newsSundayRate = rs.getInt(2);
                }

                int weeklyAmount = weekDays * newsWeeklyRate;
                int sundayAmount = sundays * newsSundayRate;

                int totalAmountForCurrentNewspaper = weeklyAmount + sundayAmount;

                totalAmount[i] = totalAmountForCurrentNewspaper;

                System.out.println("WEEKDAY AMOUNT for newspaper : "+weeklyAmount);
                System.out.println("SUNDAY AMOUNT for newspaper : "+sundayAmount);
                System.out.println("TOTAL AMOUNT TO BE PAID : "+totalAmountForCurrentNewspaper);


                //ADD CONTENT IN THE TABLE
                DefaultTableModel model = (DefaultTableModel)billDetailsTable.getModel(); 

                Object[] cell = new Object[7];

                cell[0] = i+1;
                //cell[1] = newspaperID[i];
                cell[1] = newspaperName[i];
                cell[2] = newsWeeklyRate;
                cell[3] = newsSundayRate;
                cell[4] = billStartDate;
                cell[5] = dateOfBilling;
                cell[6] = totalAmountForCurrentNewspaper;

                model.addRow(cell);

                //**************** CALCULATE DUE AMOUNT **************
                rs = st.executeQuery("select due_amount from customer_newspaper where subscription_id='"+subscriptionID[i]+"'");
                if(rs.next())
                {
                    totalDueAmount = totalDueAmount + rs.getInt(1);
                }

             }//end of for loop
        
        }//end of try
        
        //When previous billing date is same as current date 
        /*catch(DontGenerateBillException e)
        {
            
        }
        */
        catch(Exception e)
        {
            System.out.println("HERE IS THE WEEKDAY ERROR");
            JOptionPane.showMessageDialog(null,e);
        }

        int total = 0;
        for(int i=0; i<subscriptionCount; i++){
            total = total + totalAmount[i];
            System.out.println(i);
        }
        
        System.out.println("\n\n TOTAL AMOUNT TO BE PAID BY CUSTOMER : "+total);
        
        
        subTotalAmountTextField.setText(String.valueOf(total));
        totalDueAmountTextField.setText(String.valueOf(totalDueAmount));
        
        total = total + totalDueAmount;
        totalAmountTextField.setText(String.valueOf(total));
        
        //Add values in table
        
        
        
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void custNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custNameTextFieldActionPerformed

    private void custEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custEmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custEmailTextFieldActionPerformed

    private void custAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custAddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custAddressTextFieldActionPerformed

    private void custGenderTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custGenderTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custGenderTextFieldActionPerformed

       // ******************* FOCUS GAINED AND LOST *************
    private void totalDueAmountTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_totalDueAmountTextFieldFocusLost
        // TODO add your handling code here:
        totalDueAmountTextField.setEditable(false);
    }//GEN-LAST:event_totalDueAmountTextFieldFocusLost

    private void totalDueAmountTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_totalDueAmountTextFieldFocusGained
        // TODO add your handling code here:\
        totalDueAmountTextField.setEditable(false);
    }//GEN-LAST:event_totalDueAmountTextFieldFocusGained

    private void custNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_custNameTextFieldFocusGained
        // TODO add your handling code here:
        custNameTextField.setEditable(false);
    }//GEN-LAST:event_custNameTextFieldFocusGained

    private void custNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_custNameTextFieldFocusLost
        // TODO add your handling code here:
        custNameTextField.setEditable(false);
    }//GEN-LAST:event_custNameTextFieldFocusLost

    private void custEmailTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_custEmailTextFieldFocusGained
        // TODO add your handling code here:
        custEmailTextField.setEditable(false);
    }//GEN-LAST:event_custEmailTextFieldFocusGained

    private void custEmailTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_custEmailTextFieldFocusLost
        // TODO add your handling code here:
        custEmailTextField.setEditable(false);
    }//GEN-LAST:event_custEmailTextFieldFocusLost

    private void custAddressTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_custAddressTextFieldFocusGained
        // TODO add your handling code here:
        custAddressTextField.setEditable(false);
    }//GEN-LAST:event_custAddressTextFieldFocusGained

    private void custAddressTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_custAddressTextFieldFocusLost
        // TODO add your handling code here:
        custAddressTextField.setEditable(false);
    }//GEN-LAST:event_custAddressTextFieldFocusLost

    private void custGenderTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_custGenderTextFieldFocusGained
        // TODO add your handling code here:
        custGenderTextField.setEditable(false);
    }//GEN-LAST:event_custGenderTextFieldFocusGained

    private void custGenderTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_custGenderTextFieldFocusLost
        // TODO add your handling code here:
        custGenderTextField.setEditable(false);
    }//GEN-LAST:event_custGenderTextFieldFocusLost

    private void generateBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateBillButtonActionPerformed
        // TODO add your handling code here:
        
        String cust_contact_no = contactNumberTextField.getText();
        String totalAmountTField = totalAmountTextField.getText(); 
        
        //Generate bill Save bill in pdf file
        String custName = custNameTextField.getText();
        String custContactNo = contactNumberTextField.getText();
        String custEmail = custEmailTextField.getText();
        String custAddress = custAddressTextField.getText();
        
        String path = "C:\\Users\\shaun\\Documents\\NetBeansProjects\\Newspaper Billing System\\Bill PDFs\\";
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        
        try
        {
            //Check if customer is eneterd
            if(cust_contact_no.equals(""))
            {
                throw new NoCustomerSelectedExeption();
            }
            
            //Check if amount is 0
            else if(totalAmountTField.equals("0"))
            {
                throw new ZeroAmountException();
            }
            
            PdfWriter.getInstance(doc, new FileOutputStream(path+""+custName+" "+dateLabel.getText()+".pdf"));
            
            doc.open();
            
            //1st PARAGRAPH
            Paragraph para1 = new Paragraph("         ------------------------------ Newspaper Billing Management System ------------------------------\n\nShirude Newspaper Agency \nContact No. : (+91) 00000 00021 \nAddress : Nashik \n\n" );
            doc.add(para1);
            
            //2nd PRAGRAPH
            Paragraph para2 = new Paragraph("Date & Time : "+dateLabel.getText()+"  "+timeLabel.getText()+"\n\nCustomer Details     :      Name                  :  "+custName+"\n                                       Contact Number  :  "+custContactNo+"\n                                       Email ID               :  "+custEmail+"\n                                       Address               :  "+custAddress+"\n\n\n");
            doc.add(para2);
            
            //Subscription PRAGRAPH
            Paragraph sub = new Paragraph("          Subscription Details : \n\n");
            doc.add(sub);
            
            //TABLE for subscription details
            PdfPTable subscriptionDetailsTable = new PdfPTable(5);
            /* JTABLE DETAILS
            cell[0] = i+1;
                //cell[1] = newspaperID[i];
                cell[1] = newspaperName[i];
                cell[2] = newsWeeklyRate;
                cell[3] = newsSundayRate;
                cell[4] = billStartDate;
                cell[5] = dateOfBilling;
                cell[6] = totalAmountForCurrentNewspaper;

            */
            subscriptionDetailsTable.addCell("\n Sr. No \n ");
            subscriptionDetailsTable.addCell("\n Newspaper Name \n ");
            subscriptionDetailsTable.addCell("\n Date of Bill Start \n ");
            subscriptionDetailsTable.addCell("\n Date of Billing \n ");
            subscriptionDetailsTable.addCell("\n Sub Total \n ");
            
            for(int i=0; i<billDetailsTable.getRowCount(); i++)
            {
                String srNo = billDetailsTable.getValueAt(i, 0).toString();
                String newspaperName = billDetailsTable.getValueAt(i, 1).toString();
                String billStartDate = billDetailsTable.getValueAt(i, 4).toString();
                String dateOfBilling = billDetailsTable.getValueAt(i, 5).toString();
                String subTotal = billDetailsTable.getValueAt(i, 6).toString();
                
                subscriptionDetailsTable.addCell("\n "+srNo+" \n ");
                subscriptionDetailsTable.addCell("\n "+newspaperName+" \n ");
                subscriptionDetailsTable.addCell("\n "+billStartDate+" \n ");
                subscriptionDetailsTable.addCell("\n "+dateOfBilling+" \n ");
                subscriptionDetailsTable.addCell("\n Rs. "+subTotal+" \n ");        
            }
            doc.add(subscriptionDetailsTable);
            
            
            //Line break paragraph
            //Subscription PRAGRAPH
            Paragraph lineBreak = new Paragraph("\n");
            doc.add(lineBreak);       
            
            
            //Due amount table 
            PdfPTable dueAmountTable = new PdfPTable(2);
            dueAmountTable.addCell(" Due Amount ");
            dueAmountTable.addCell(" Rs. "+totalDueAmountTextField.getText());
            doc.add(dueAmountTable);
            
            
            //Line break paragraph
            //Subscription PRAGRAPH
            Paragraph lineBreak1 = new Paragraph("\n");
            doc.add(lineBreak1);       
            
            //Total amount table 
            PdfPTable totalAmountTable = new PdfPTable(2);
            totalAmountTable.addCell(" Total Amount ");
            totalAmountTable.addCell(" Rs. "+totalAmountTextField.getText());
            doc.add(totalAmountTable);
           
            
            
            //Newspaper Detao;s PRAGRAPH
            Paragraph newsRates = new Paragraph("\n\n          Newspaper Prices (in Indian Rupees)  : \n\n");
            doc.add(newsRates);
            
            //New table for newwspaper rates
            PdfPTable newsRateTable = new PdfPTable(4);
            newsRateTable.addCell(" Sr. No ");
            newsRateTable.addCell(" Newspaper Name ");
            newsRateTable.addCell(" Weekdays Rate ");
            newsRateTable.addCell(" Sunday Rate ");
            for(int i=0; i<billDetailsTable.getRowCount(); i++)
            {
                String srNo = billDetailsTable.getValueAt(i, 0).toString();
                String newspaperName = billDetailsTable.getValueAt(i, 1).toString();
                String weekdaysRate = billDetailsTable.getValueAt(i, 2).toString();
                String sundayRate = billDetailsTable.getValueAt(i, 3).toString();
                
                newsRateTable.addCell(srNo);
                newsRateTable.addCell(newspaperName);
                newsRateTable.addCell(weekdaysRate);
                newsRateTable.addCell(sundayRate);        
            }
            doc.add(newsRateTable);
          
            //3rd PARAGRAPH
            Paragraph para3 = new Paragraph("\n\n        Total Amount to be paid     :     (Rs.) "+totalAmountTextField.getText()+"\n\n\n                        ----------------------------- Thank You ! Happy Reading ! -----------------------------");
            doc.add(para3);
            
            //Close the doc
            doc.close();
            
            JOptionPane.showMessageDialog(null, "Bill has been Generated Successfully"); 
            
            setVisible(false);
            new Billing().setVisible(true);
            
        }
        
        //No customer is selected 
        catch(NoCustomerSelectedExeption e)
        {
            JOptionPane.showMessageDialog(null, "Please enter a customer to generate bill");
        }
        
        //Zero amount in total amount
        catch(ZeroAmountException e)
        {
            JOptionPane.showMessageDialog(null, "Bill cannot be generated. Total amount = 0");
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
        for(int i=0; i<subscriptionCount; i++)
        {
            System.out.println(i+1);
        
            try
            {
                Connection con = ConnectionProvider.getCon();
                Statement st = con.createStatement();

                ResultSet rs;
                   
                //Update billStartDate in customer_newspaper table
                SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");

                //dateOfBillingDate = new Date(dateOfBillingDate.getTime()+2);
                
                Date todaysDate = new Date();
                dFormat.format(todaysDate);
                String dateOfBilling = dFormat.format(todaysDate);

                //final Calendar calendar = Calendar.getInstance();
                //calendar.setTime(dateOfBillingDate);
                //calendar.add(Calendar.DAY_OF_YEAR, 1);
                
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                Calendar c = Calendar.getInstance();
                c.setTime(sdf.parse(dateOfBilling));
                c.add(Calendar.DATE, 1);  // number of days to add
                dateOfBilling = sdf.format(c.getTime());  // dt is now the new date
                
                

                System.out.println(dateOfBilling+" SSASA");
                //System.out.println(dateOfBilling);
                //SET NEW BILL START DATE AND BILL PENDING AND DUE AMOUNT
                st.executeUpdate("update customer_newspaper set bill_start_date = '"+dateOfBilling+"',bill_pending='No', due_amount=null where subscription_id= '"+subscriptionID[i]+"'");
            
            }
            catch(Exception e)
            {
                System.out.println("HH");
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_generateBillButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Billing().setVisible(true);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void totalAmountTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_totalAmountTextFieldFocusGained
        // TODO add your handling code here:
        totalAmountTextField.setEditable(false);
    }//GEN-LAST:event_totalAmountTextFieldFocusGained

    private void totalAmountTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_totalAmountTextFieldFocusLost
        // TODO add your handling code here:
        totalAmountTextField.setEditable(false);
    }//GEN-LAST:event_totalAmountTextFieldFocusLost

    private void totalAmountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalAmountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalAmountTextFieldActionPerformed

    private void subTotalAmountTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_subTotalAmountTextFieldFocusGained
        // TODO add your handling code here:
        subTotalAmountTextField.setEditable(false);
    }//GEN-LAST:event_subTotalAmountTextFieldFocusGained

    private void subTotalAmountTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_subTotalAmountTextFieldFocusLost
        // TODO add your handling code here:
        subTotalAmountTextField.setEditable(false);
    }//GEN-LAST:event_subTotalAmountTextFieldFocusLost

    private void subTotalAmountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subTotalAmountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subTotalAmountTextFieldActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
        //setVisible(false);
        //dispose();
    }//GEN-LAST:event_formWindowLostFocus
    // ************ FOCUS GAINED AND LOST ****************
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable billDetailsTable;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField contactNumberTextField;
    private javax.swing.JTextField custAddressTextField;
    private javax.swing.JTextField custEmailTextField;
    private javax.swing.JTextField custGenderTextField;
    private javax.swing.JTextField custNameTextField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton generateBillButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton resetButton;
    private javax.swing.JTextField subTotalAmountTextField;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JTextField totalAmountTextField;
    private javax.swing.JTextField totalDueAmountTextField;
    // End of variables declaration//GEN-END:variables

    private static class NoCustomerSelectedExeption extends Exception {}

    private static class ZeroAmountException extends Exception {}

    

  

}
