import Project.ConnectionProvider;
import java.awt.Color;
import static java.lang.Character.isDigit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.swing.JOptionPane;
import java.time.*;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shaun
 */
public class DeleteAdmin extends javax.swing.JFrame {

    /**
     * Creates new form DeleteAdmin
     */
    public DeleteAdmin() {
        initComponents();
        
        adminNameTextField.setEditable(false);
        adminUsernameTextField.setEditable(false);
        adminPasswordTextField.setEditable(false);
        adminEmailTextField.setEditable(false);
        adminContactNoTextField.setEditable(false);
        isSuperadminComboBox.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        contactNumberLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        admnUsernameSearchTextField = new javax.swing.JTextField();
        adminContactNoTextField = new javax.swing.JTextField();
        deleteAdmin = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        adminNameTextField = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        searchButton = new javax.swing.JButton();
        contactNumberFormLabel1 = new javax.swing.JLabel();
        adminUsernameTextField = new javax.swing.JTextField();
        contactNumberFormLabel2 = new javax.swing.JLabel();
        adminPasswordTextField = new javax.swing.JTextField();
        contactNumberFormLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        adminEmailTextField = new javax.swing.JTextField();
        activateLabel1 = new javax.swing.JLabel();
        isSuperadminComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(290, 220));
        setMaximumSize(new java.awt.Dimension(995, 540));
        setMinimumSize(new java.awt.Dimension(995, 540));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jLabel1.setText("Delete Admin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 910, 10));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 910, 20));

        contactNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactNumberLabel.setText("Admin Username");
        getContentPane().add(contactNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, 20));

        emailLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailLabel.setText("Email");
        getContentPane().add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, -1, 20));

        genderLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderLabel.setText("Contact No.");
        getContentPane().add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, -1, 20));

        admnUsernameSearchTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        admnUsernameSearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admnUsernameSearchTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(admnUsernameSearchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 200, -1));

        adminContactNoTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminContactNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminContactNoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(adminContactNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 250, -1));

        deleteAdmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash_icon.png"))); // NOI18N
        deleteAdmin.setText("  Delete");
        deleteAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAdminActionPerformed(evt);
            }
        });
        getContentPane().add(deleteAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 140, 50));

        resetButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset_icon.png"))); // NOI18N
        resetButton.setText("  Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 140, 50));

        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel_icon.png"))); // NOI18N
        cancelButton.setText("  Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 450, 130, 50));

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameLabel.setText("Name");
        getContentPane().add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, 20));

        adminNameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(adminNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 250, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 910, 20));

        searchButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search_icon.png"))); // NOI18N
        searchButton.setText("  Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 130, 40));

        contactNumberFormLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactNumberFormLabel1.setText("Password");
        getContentPane().add(contactNumberFormLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, 20));

        adminUsernameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminUsernameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(adminUsernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 250, -1));

        contactNumberFormLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactNumberFormLabel2.setText(" ");
        getContentPane().add(contactNumberFormLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, 20));

        adminPasswordTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminPasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPasswordTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(adminPasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 250, -1));

        contactNumberFormLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactNumberFormLabel3.setText("Username");
        getContentPane().add(contactNumberFormLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, 20));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 940, 10));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 940, 10));

        adminEmailTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminEmailTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(adminEmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 250, -1));

        activateLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        activateLabel1.setText("Is SuperAdmin");
        getContentPane().add(activateLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, -1, -1));

        isSuperadminComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        isSuperadminComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));
        getContentPane().add(isSuperadminComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 220, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete_admin.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admnUsernameSearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admnUsernameSearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admnUsernameSearchTextFieldActionPerformed

    private void adminContactNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminContactNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminContactNoTextFieldActionPerformed

    private void deleteAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAdminActionPerformed
        // TODO add your handling code here:

        int confirm = JOptionPane.showConfirmDialog(null, "Do you really want to Delete this Admin","Delete Admin Records", JOptionPane.YES_NO_OPTION);
        
        if(confirm==0)
        {

           // String adminUsername = adminUsernameTextField.getText();

            try
            {
                Connection con = ConnectionProvider.getCon();
                Statement st = con.createStatement();

                st.executeUpdate("delete from Admin where admin_username='"+adminUsernameSearch+"' ");

                JOptionPane.showMessageDialog(null, "Successfully Deleted");

                setVisible(false);
                new DeleteAdmin().setVisible(true);
            }

            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
                setVisible(false);
                new DeleteAdmin().setVisible(true);
            }
        }

        
    }//GEN-LAST:event_deleteAdminActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new DeleteAdmin().setVisible(true);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        //System.exit(0);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void adminNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminNameTextFieldActionPerformed

    String adminUsernameSearch = "";
    
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:

        adminUsernameSearch = admnUsernameSearchTextField.getText();
        try
        {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from Admin where admin_username='"+adminUsernameSearch+"'");

            if(rs.next())
            {
                //Search and get all the details from customer table then put them on the text fields
                //(1) is newsID
                adminNameTextField.setText(rs.getString(2));
                adminUsernameTextField.setText(rs.getString(3));
                adminPasswordTextField.setText(rs.getString(4));
                adminContactNoTextField.setText(rs.getString(5));
                adminEmailTextField.setText(rs.getString(6));
                isSuperadminComboBox.setSelectedItem(rs.getString(7));

                admnUsernameSearchTextField.setEditable(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Admin does Not Exist");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
            setVisible(false);
            new DeleteAdmin().setVisible(true);
        }
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void adminUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminUsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminUsernameTextFieldActionPerformed

    private void adminPasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminPasswordTextFieldActionPerformed

    private void adminEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminEmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminEmailTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activateLabel1;
    private javax.swing.JTextField adminContactNoTextField;
    private javax.swing.JTextField adminEmailTextField;
    private javax.swing.JTextField adminNameTextField;
    private javax.swing.JTextField adminPasswordTextField;
    private javax.swing.JTextField adminUsernameTextField;
    private javax.swing.JTextField admnUsernameSearchTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel contactNumberFormLabel1;
    private javax.swing.JLabel contactNumberFormLabel2;
    private javax.swing.JLabel contactNumberFormLabel3;
    private javax.swing.JLabel contactNumberLabel;
    private javax.swing.JButton deleteAdmin;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JComboBox<String> isSuperadminComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
