import Project.ConnectionProvider;
import java.awt.Color;
import static java.lang.Character.isDigit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.swing.JOptionPane;
import java.time.*;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shaun
 */
public class SubscriptionDetailsByCustomer extends javax.swing.JFrame {

    /**
     * Creates new form SubscriptionDetailsByCustomer
     */
    public SubscriptionDetailsByCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerDetailsHeaderLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        subscriptionDetailsTable = new javax.swing.JTable();
        printButton = new javax.swing.JButton();
        clsoeButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        confirmButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        customerContactNumberTextField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 190));
        setMaximumSize(new java.awt.Dimension(1150, 600));
        setMinimumSize(new java.awt.Dimension(1150, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1150, 600));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerDetailsHeaderLabel.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        customerDetailsHeaderLabel.setText("Subscription Details");
        getContentPane().add(customerDetailsHeaderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 1130, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1130, 10));

        subscriptionDetailsTable.setBorder(new javax.swing.border.MatteBorder(null));
        subscriptionDetailsTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        subscriptionDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "null", "null", "null", "null", "Title 5"
            }
        ));
        subscriptionDetailsTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                subscriptionDetailsTableFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(subscriptionDetailsTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 1130, 280));

        printButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        printButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print_icon.png"))); // NOI18N
        printButton.setText("  Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });
        getContentPane().add(printButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 210, 40));

        clsoeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clsoeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel_icon.png"))); // NOI18N
        clsoeButton.setText("  Close");
        clsoeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clsoeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clsoeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 530, 200, 40));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 1130, 10));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 1120, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/subscription_details.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 1130, 10));

        confirmButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        confirmButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search_icon.png"))); // NOI18N
        confirmButton.setText("  Find");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 140, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Constumer Contact No : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 180, 20));

        customerContactNumberTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        customerContactNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerContactNumberTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(customerContactNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 230, 30));

        backButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back_icon.png"))); // NOI18N
        backButton.setText("  Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 140, 40));

        refreshButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh_icon.png"))); // NOI18N
        refreshButton.setText(" Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        getContentPane().add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, 140, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subscriptionDetailsTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_subscriptionDetailsTableFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_subscriptionDetailsTableFocusGained

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // TODO add your handling code here:

        try
        {
            subscriptionDetailsTable.print(JTable.PrintMode.FIT_WIDTH);
        }
        catch(Exception e)
        {
        }
    }//GEN-LAST:event_printButtonActionPerformed

    private void clsoeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clsoeButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_clsoeButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        
        String custContactNo = customerContactNumberTextField.getText();
        
        try
        {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs;
            
            //Check if contact number is present
            rs = st.executeQuery("select * from Customer where cust_contact_no ='"+custContactNo+"'");
            if(!rs.next())
            {
                throw new NoCustomerException();
            }
            //Fetch subscriptions 
            rs = st.executeQuery("select * from customer_newspaper where cust_contact_no ='"+custContactNo+"'");
            //IF no subscriptions exist
            if(!rs.next())
            {
                throw new NoSubscriptionsException();
            }
            rs = st.executeQuery("select * from customer_newspaper where cust_contact_no ='"+custContactNo+"'");
            subscriptionDetailsTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        
        //No customer exists
        catch(NoCustomerException e)
        {
            JOptionPane.showMessageDialog(null, "Customer does not exist ");
        }
        
        //No subscriptions exist
        catch(NoSubscriptionsException e)
        {
            JOptionPane.showMessageDialog(null, "No subscriptions for this Customer No. ");
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void customerContactNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerContactNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerContactNumberTextFieldActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
        //setVisible(false);
        //dispose();
    }//GEN-LAST:event_formWindowLostFocus

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        
        //Go back to details frame
        new SubscriptionDetails().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        new SubscriptionDetailsByCustomer().setVisible(true);
        //System.exit(0);
    }//GEN-LAST:event_refreshButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubscriptionDetailsByCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubscriptionDetailsByCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubscriptionDetailsByCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubscriptionDetailsByCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubscriptionDetailsByCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton clsoeButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField customerContactNumberTextField;
    private javax.swing.JLabel customerDetailsHeaderLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton printButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JTable subscriptionDetailsTable;
    // End of variables declaration//GEN-END:variables

    //User defined exceptions
    private static class NoSubscriptionsException extends Exception {}
    private static class NoCustomerException extends Exception {}
}
