
import DateCallculator.CalculateDays;
import Project.ConnectionProvider;
import java.awt.Color;
import static java.lang.Character.isDigit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.swing.JOptionPane;
import java.time.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shaun
 */
public class UpdateSubscription extends javax.swing.JFrame {

    /**
     * Creates new form UpdateSubscription
     */
    public UpdateSubscription() {
        initComponents();
        
        //Disable editables
        customerNameTextField.setEditable(false);
        customerContactNumberTextField.setEditable(false);
        newspaperIDTextField.setEditable(false);
        newspaperNameTextField.setEditable(false);
        subscriptionDateTextField.setEditable(false);
        lastDateOfBillingTextField.setEditable(false);
        subscriptionEndDateTextField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        subscriptionNoLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        contactNumberFormLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        subscriptionIDTextField = new javax.swing.JTextField();
        customerContactNumberTextField = new javax.swing.JTextField();
        newspaperIDTextField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        updateButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        customerNameTextField = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        searchButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        genderLabel1 = new javax.swing.JLabel();
        lastDateOfBillingTextField = new javax.swing.JTextField();
        addressLabel1 = new javax.swing.JLabel();
        newspaperNameTextField = new javax.swing.JTextField();
        subscriptionDateTextField = new javax.swing.JTextField();
        genderLabel2 = new javax.swing.JLabel();
        subscriptionEndDateTextField = new javax.swing.JTextField();
        subscriptionStatusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(330, 190));
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update_subscription.png"))); // NOI18N
        jLabel1.setText("  Update Subscription");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 930, 20));

        subscriptionNoLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subscriptionNoLabel.setText("Subscription ID.");
        getContentPane().add(subscriptionNoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, 20));

        addressLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addressLabel.setText("Subscription Status");
        getContentPane().add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, 20));

        emailLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailLabel.setText("Newspaper ID");
        getContentPane().add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, 20));

        contactNumberFormLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactNumberFormLabel.setText("Customer Contact No.      +91");
        getContentPane().add(contactNumberFormLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 20));

        genderLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderLabel.setText("Subscription Date");
        getContentPane().add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, 20));

        subscriptionIDTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subscriptionIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subscriptionIDTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(subscriptionIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 200, -1));

        customerContactNumberTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        customerContactNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerContactNumberTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(customerContactNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 200, -1));

        newspaperIDTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        newspaperIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newspaperIDTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(newspaperIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 250, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 940, 10));

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/activation_icon.png"))); // NOI18N
        updateButton.setText("  Activation Status");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 240, 50));

        resetButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset_icon.png"))); // NOI18N
        resetButton.setText("  Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 120, 50));

        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel_icon.png"))); // NOI18N
        cancelButton.setText("  Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 500, 120, 50));

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameLabel.setText("Customer Name");
        getContentPane().add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 20));

        customerNameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        customerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(customerNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 250, -1));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 940, 10));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 930, 20));

        searchButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search_icon.png"))); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 120, 40));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 930, 10));

        genderLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderLabel1.setText("Last date of billing");
        getContentPane().add(genderLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, 20));

        lastDateOfBillingTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lastDateOfBillingTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastDateOfBillingTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(lastDateOfBillingTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 230, -1));

        addressLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addressLabel1.setText("Newspaper Name");
        getContentPane().add(addressLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, 20));

        newspaperNameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(newspaperNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 250, -1));

        subscriptionDateTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        subscriptionDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subscriptionDateTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(subscriptionDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 230, -1));

        genderLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderLabel2.setText("Subscription End Date");
        getContentPane().add(genderLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, -1, 20));

        subscriptionEndDateTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        subscriptionEndDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subscriptionEndDateTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(subscriptionEndDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 230, -1));

        subscriptionStatusLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        subscriptionStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subscriptionStatusLabel.setText("Status");
        getContentPane().add(subscriptionStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subscriptionIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subscriptionIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subscriptionIDTextFieldActionPerformed

    private void customerContactNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerContactNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerContactNumberTextFieldActionPerformed

    private void newspaperIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newspaperIDTextFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_newspaperIDTextFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        /*
        String custContactNoSearch = subscriptionIDTextField.getText();
        String custName = customerNameTextField.getText();
        String custContactNo = customerContactNumberFormTextField.getText();
        String custEmail = newspaperIDTextField.getText();
        String custAddress = addressTextField.getText();
        String custGender = (String)genderComboBox.getSelectedItem();
        */
        
        String subscriptionStatus = subscriptionStatusLabel.getText();
        String subscriptionID = subscriptionIDTextField.getText();
        
  
        //Generate date with sql format
        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        //For current Date
        Date todaysDate = new Date();
        dFormat.format(todaysDate);
        //Assign to strin()g
        String currentDate = dFormat.format(todaysDate);
        
        
        System.out.println("END DATE "+currentDate);
        
        int confirm;
        if(subscriptionStatus.equals("Active"))
            confirm = JOptionPane.showConfirmDialog(null, "Do you really want to Deactivate this Subscription","Select", JOptionPane.YES_NO_OPTION);
        else
            confirm = JOptionPane.showConfirmDialog(null, "Do you really want to Acivate this Subscription","Select", JOptionPane.YES_NO_OPTION);
        
        String status="";
        
        // THESE VARIABLES ARE USED TO UPDATE DUE AMOUNT OF PREVIOUS SUBSCRIPTION
        String billPending="";
        String newspaperID="";
        int weekdayRate = 0;
        int sundayRate = 0;
        Date billStartDateForDues = null;
        Date subscriptionEndDateForDues = null;
        int totalDues = 0;
        //*******************************************************************
        
        if(confirm == 0)
        {
            try
            {
                Connection con = ConnectionProvider.getCon();
                Statement st = con.createStatement();
                ResultSet rs;
                
                
                
                if(subscriptionStatus.equals("Active"))
                {
                    status = "Inactive";
                    String billEndDate = currentDate;
                    st.executeUpdate("update customer_newspaper set subscription_status='"+status+"', subscription_end_date='"+billEndDate+"' where subscription_id='"+subscriptionID+"'");

                    JOptionPane.showMessageDialog(null, "Subscription has been Deacticated ");

                    setVisible(false);
                    new UpdateSubscription().setVisible(true);
                }
                //When sub reactivated
                else
                {
                    rs = st.executeQuery("select bill_pending, news_id from customer_newspaper where subscription_id='"+subscriptionID+"'");
                    if(rs.next())
                    {
                        billPending = rs.getString(1); 
                        newspaperID = rs.getString(2);
                    }
                    
                    //Later used for continue option
                    int confirm1;
                    
                    if(billPending.equals("Yes"))
                    {
                        //Fetch the dates
                        rs = st.executeQuery("select bill_start_date, subscription_end_date from customer_newspaper where subscription_id='"+subscriptionID+"'");
                        if(rs.next())
                        {
                            billStartDateForDues = rs.getDate(1);
                            subscriptionEndDateForDues = rs.getDate(2);
                            
                            System.out.println(billStartDateForDues);
                            System.out.println(subscriptionEndDateForDues);
                            
                            //Convert them to normal date pattern
                             dFormat.format(billStartDateForDues);
                             dFormat.format(subscriptionEndDateForDues);
                            
                        }

                        //Fetch the rates
                        rs = st.executeQuery("select news_weekday_rate, news_sunday_rate from Newspaper where news_id ='"+newspaperID+"'");
                        if(rs.next())
                        {
                            weekdayRate = rs.getInt(1);
                            sundayRate = rs.getInt(2);
                            
                            
                             /*
                            The function CalculateDays will calculate days from start date to end_date with inclusive of start and end dats
                            But when new bill start date is assigned, next time when bill is genereated we don't need to include the start date.
                            
                            boolean firstTimeBill = false;
                            if(billStartDateForDues.equals(subscriptionEndDateForDues))
                            {
                                firstTimeBill = true;
                            }*/
                            
                            //Calculate the amount from start day to previous subscription end date;
                            CalculateDays cd = new CalculateDays();
                            int weekDays = cd.getWorkingDaysBetweenTwoDates(billStartDateForDues, subscriptionEndDateForDues, true);
                            int sundays = cd.getSundaysBetweenTwoDates(billStartDateForDues, subscriptionEndDateForDues, true);   
                            
                            int weekdayDues = weekDays * weekdayRate;
                            int sundayDues = sundays * sundayRate;

                            totalDues = weekdayDues + sundayDues;
                            
                            rs = st.executeQuery("select due_amount from customer_newspaper where subscription_id='"+subscriptionID+"'");
                            if(rs.next())
                            {
                                int previousDues = rs.getInt(1);
                                totalDues = totalDues + previousDues;
                                st.executeUpdate("update customer_newspaper set due_amount='"+totalDues+"' where subscription_id='"+subscriptionID+"'");
                            }
                            else
                            {
                                st.executeUpdate("update customer_newspaper set due_amount='"+totalDues+"' where subscription_id='"+subscriptionID+"'");
                            }       
                            //int confirm = JOptionPane.showConfirmDialog(null, "Changes made in Dues column. Do you want to continue ?"."Confirmation",JOptionPane.YES_NO_OPTION);
                            JOptionPane.showMessageDialog(null, "Dues have been added");
                            
                    }
                    
                    
                    status = "Active";
                    String subscriptionDate = currentDate;
                    //String subscriptionEndDate = "0000-00-00";
                    String billStartDate = currentDate;
                    st.executeUpdate("update customer_newspaper set subscription_status='"+status+"', subscription_date='"+subscriptionDate+"', bill_start_date = '"+billStartDate+"' , subscription_end_date=null where subscription_id='"+subscriptionID+"'");
                
                    JOptionPane.showMessageDialog(null, "Subscription has been Activated ");

                    setVisible(false);
                    new UpdateSubscription().setVisible(true);
                }
                
            }

            }

            catch(SQLIntegrityConstraintViolationException e)
            {
                JOptionPane.showMessageDialog(null,"Customer with this Contact No. already exists. Please add another Contact Number");
            }

            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
        
        }

    }//GEN-LAST:event_updateButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new UpdateSubscription().setVisible(true);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        //System.exit(0);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void customerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameTextFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:

        String subscriptionID = subscriptionIDTextField.getText();
        try
        {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from customer_newspaper where subscription_id='"+subscriptionID+"'");

            if(rs.next())
            {
                //Changing date format
                //Generate date with sql format
                SimpleDateFormat dFormat = new SimpleDateFormat("dd-MM-yyyy");
                
                //SUBSCRIPTION DATE
                Date subscriptionDateD = rs.getDate(6);
                dFormat.format(subscriptionDateD);
                //Assign to string
                String subscriptionDate = dFormat.format(subscriptionDateD);
                System.out.println("HERE0");
                System.out.println(rs.getDate(6));
                

                
                
                System.out.println("HERE1");
                
                //Search and get all the details from customer table then put them on the text fields
                customerContactNumberTextField.setText(rs.getString(2));
                customerNameTextField.setText(rs.getString(3));
                newspaperIDTextField.setText(rs.getString(4));
                newspaperNameTextField.setText(rs.getString(5));
                subscriptionDateTextField.setText(subscriptionDate);    //6
                
                //BILL START DATE
                System.out.println(rs.getString(7));
                //String billStartDate = rs.getString(7);
                Date billStartDateD = rs.getDate(7);
                dFormat.format(billStartDateD);
                //Assign to string
                String billStartDate = dFormat.format(billStartDateD);
                
                if(billStartDate.equals(subscriptionDate) && rs.getString(10).equals("Yes"))
                {
                    lastDateOfBillingTextField.setText(" - ");  //7
                }
                else
                {
                    //Date billStartDateD = rs.getDate(7);
                    dFormat.format(billStartDateD);
                    //Assign to string
                    //billStartDate = dFormat.format(billStartDateD);
                    lastDateOfBillingTextField.setText(billStartDate);  //7
                }
                //subscriptionEndDateTextField.setText(rs.getString(8));
                
                if(rs.getString(8)==null || rs.getString(8).equals("0000-00-00"))
                    subscriptionEndDateTextField.setText("Subscription is still active");
                else
                {
                    //SUBSCRIPTION END DATE
                    Date subscriptionEndDateD = rs.getDate(8);
                    dFormat.format(subscriptionEndDateD);
                    //Assign to string
                    String subscriptionEndDate = dFormat.format(subscriptionEndDateD);
                    
                    subscriptionEndDateTextField.setText(subscriptionEndDate);
                }
                
                
                //Label active or inactive\
                subscriptionStatusLabel.setOpaque(true);
                subscriptionStatusLabel.setBackground(Color.BLACK);
                if(rs.getString(9).equals("Active"))
                {
                    subscriptionStatusLabel.setForeground(Color.GREEN);
                }
                else if(rs.getString(9).equals("Inactive"))
                {
                    subscriptionStatusLabel.setForeground(Color.RED);
                }
                subscriptionStatusLabel.setText(rs.getString(9));
                
                //Cant edit ID anymore
                subscriptionIDTextField.setEditable(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Subscription does not exist");
            }
            
            String update = subscriptionStatusLabel.getText();
            if(update.equals("Active"))
            {
                updateButton.setText("Deactivate Subscription");
            }
            else if(update.equals("Inactive"))
            {
                updateButton.setText("Activate Subscription");
            }
            //updateButton.setText(subscriptionStatusTextField.getText());
        }
        catch(Exception e)
        {
            System.out.println("HERE IS THE ERROR");
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void lastDateOfBillingTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastDateOfBillingTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastDateOfBillingTextFieldActionPerformed

    private void subscriptionDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subscriptionDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subscriptionDateTextFieldActionPerformed

    private void subscriptionEndDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subscriptionEndDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subscriptionEndDateTextFieldActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
        //setVisible(false);
        //dispose();
    }//GEN-LAST:event_formWindowLostFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateSubscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateSubscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateSubscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateSubscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateSubscription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressLabel1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel contactNumberFormLabel;
    private javax.swing.JTextField customerContactNumberTextField;
    private javax.swing.JTextField customerNameTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel genderLabel1;
    private javax.swing.JLabel genderLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField lastDateOfBillingTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField newspaperIDTextField;
    private javax.swing.JTextField newspaperNameTextField;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField subscriptionDateTextField;
    private javax.swing.JTextField subscriptionEndDateTextField;
    private javax.swing.JTextField subscriptionIDTextField;
    private javax.swing.JLabel subscriptionNoLabel;
    private javax.swing.JLabel subscriptionStatusLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
