import Project.ConnectionProvider;
import java.awt.Color;
import static java.lang.Character.isDigit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.swing.JOptionPane;
import java.time.*;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shaun
 */
public class UpdateAdmin extends javax.swing.JFrame {

    /**
     * Creates new form UpdateAdmin
     */
    String adminUsernameSearch="";
    String adminUsername="";
    public UpdateAdmin(String admin_username) {
        initComponents();
        System.out.println("USRNENAME THIS : "+admin_username);
        
        adminUsername = admin_username;
        System.out.println("ADMIN NAME CONSTRUCTOR : "+adminUsername+"   "+admin_username);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        contactNumberLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        admnUsernameSearchTextField = new javax.swing.JTextField();
        adminContactNoTextField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        adminNameTextField = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        searchButton = new javax.swing.JButton();
        contactNumberFormLabel1 = new javax.swing.JLabel();
        adminUsernameTextField = new javax.swing.JTextField();
        contactNumberFormLabel2 = new javax.swing.JLabel();
        adminPasswordTextField = new javax.swing.JTextField();
        contactNumberFormLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        adminEmailTextField = new javax.swing.JTextField();
        activateLabel1 = new javax.swing.JLabel();
        isSuperadminComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(290, 220));
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jLabel1.setText("Edit Admin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 910, 10));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 910, 20));

        contactNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactNumberLabel.setText("Admin Username");
        getContentPane().add(contactNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, 20));

        emailLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        emailLabel.setText("Email");
        getContentPane().add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, -1, 20));

        genderLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        genderLabel.setText("Contact No.");
        getContentPane().add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, -1, 20));

        admnUsernameSearchTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        admnUsernameSearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admnUsernameSearchTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(admnUsernameSearchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 200, -1));

        adminContactNoTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminContactNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminContactNoTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(adminContactNoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 250, -1));

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/update_icon.png"))); // NOI18N
        updateButton.setText("  Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 140, 50));

        resetButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reset_icon.png"))); // NOI18N
        resetButton.setText("  Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 140, 50));

        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel_icon.png"))); // NOI18N
        cancelButton.setText("  Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 450, 130, 50));

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameLabel.setText("Name");
        getContentPane().add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, 20));

        adminNameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminNameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(adminNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 250, -1));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 910, 20));

        searchButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search_icon.png"))); // NOI18N
        searchButton.setText("  Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 130, 40));

        contactNumberFormLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactNumberFormLabel1.setText("Password");
        getContentPane().add(contactNumberFormLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, 20));

        adminUsernameTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminUsernameTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(adminUsernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 250, -1));

        contactNumberFormLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactNumberFormLabel2.setText(" ");
        getContentPane().add(contactNumberFormLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, 20));

        adminPasswordTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminPasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPasswordTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(adminPasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 250, -1));

        contactNumberFormLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactNumberFormLabel3.setText("Username");
        getContentPane().add(contactNumberFormLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, 20));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 940, 10));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 940, 10));

        adminEmailTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminEmailTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(adminEmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 250, -1));

        activateLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        activateLabel1.setText("Is SuperAdmin");
        getContentPane().add(activateLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, -1, -1));

        isSuperadminComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        isSuperadminComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));
        getContentPane().add(isSuperadminComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 220, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit_admin.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admnUsernameSearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admnUsernameSearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admnUsernameSearchTextFieldActionPerformed

    private void adminContactNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminContactNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminContactNoTextFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:

        String adminName = adminNameTextField.getText();
        String adminUsername = adminUsernameTextField.getText();
        String adminPassword = adminPasswordTextField.getText();
        String adminEmail = adminEmailTextField.getText();
        String adminContactNo = adminContactNoTextField.getText();
        String isSuperadmin = (String)isSuperadminComboBox.getSelectedItem();

        try
        {
            //Check if all fields are filled
            if(adminName.equals("") || adminUsername.equals("") || adminPassword.equals(""))
            {
                throw new NullFieldException();
            }
            
            //Check if contact number has 10 values 
            if(adminContactNo.length() != 10)
            {
                throw new AddAdmin.ContactNumberException();
            }
            
            //Check if contact number is in digits 
            for(int i=0; i < adminContactNo.length(); i++)
            {
                if(!(isDigit(adminContactNo.charAt(i))))
                {
                    throw new AddAdmin.ContactNumberException();
                }
            }

            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs;
            System.out.println("search "+adminUsernameSearch+"HEYY");
            System.out.println(adminUsername+"HEYYY");

            //If a super admin is created then show a warning confirmation box
            //int confirm=100;
            if(isSuperadmin.equals("Yes"))
            {
                int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to create a new SuperAdmin.", "Confirmation", JOptionPane.YES_NO_OPTION);
                if(confirm == JOptionPane.NO_OPTION)
                {
                    throw new StopProcessException();
                }
            }
            System.out.println("seach "+adminUsernameSearch+"HEYY");
            st.executeUpdate("update Admin set admin_name='"+adminName+"', admin_username='"+adminUsername+"', admin_password='"+adminPassword+"', admin_contact_no='"+adminContactNo+"', admin_email='"+adminEmail+"' where admin_username='"+adminUsernameSearch+"'");

            JOptionPane.showMessageDialog(null, "Successfully Updated");

            setVisible(false);
            new UpdateAdmin(adminUsername).setVisible(true);
        }

        //Fields are null
        catch(NullFieldException e)
        {
            //new NullFieldException();
            JOptionPane.showMessageDialog(null,"Please fill all the details");
        }
        
        //Contact number is not right
        catch(AddAdmin.ContactNumberException e)
        {
            JOptionPane.showMessageDialog(null,"Please enter a valid Contact Number");
        }

        //Stop Process and DO NOTHING
        catch(StopProcessException e){}

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new UpdateAdmin(adminUsername).setVisible(true);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
        //System.exit(0);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void adminNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminNameTextFieldActionPerformed
   
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:

        adminUsernameSearch = admnUsernameSearchTextField.getText();
        
        try
        {
            if(adminUsername.equals(adminUsernameSearch))
            {
                throw new CurrentAdminUsernameExcpetion();
            }
            
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from Admin where admin_username='"+adminUsernameSearch+"'");

            if(rs.next())
            {
                //Search and get all the details from customer table then put them on the text fields
                //(1) is newsID
                adminNameTextField.setText(rs.getString(2));
                adminUsernameTextField.setText(rs.getString(3));
                adminPasswordTextField.setText(rs.getString(4));
                adminContactNoTextField.setText(rs.getString(5));
                adminEmailTextField.setText(rs.getString(6));
                isSuperadminComboBox.setSelectedItem(rs.getString(7));

                admnUsernameSearchTextField.setEditable(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Admin does Not Exist");
            }
        }
        
        //Current Username Excpeiton
        catch(CurrentAdminUsernameExcpetion e)
        {
            JOptionPane.showMessageDialog(null, "Cannot edit details for Admin in use.");
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_searchButtonActionPerformed

    private void adminUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminUsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminUsernameTextFieldActionPerformed

    private void adminPasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminPasswordTextFieldActionPerformed

    private void adminEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminEmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminEmailTextFieldActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
        //setVisible(false);
        //dispose();
    }//GEN-LAST:event_formWindowLostFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateAdmin("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activateLabel1;
    private javax.swing.JTextField adminContactNoTextField;
    private javax.swing.JTextField adminEmailTextField;
    private javax.swing.JTextField adminNameTextField;
    private javax.swing.JTextField adminPasswordTextField;
    private javax.swing.JTextField adminUsernameTextField;
    private javax.swing.JTextField admnUsernameSearchTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel contactNumberFormLabel1;
    private javax.swing.JLabel contactNumberFormLabel2;
    private javax.swing.JLabel contactNumberFormLabel3;
    private javax.swing.JLabel contactNumberLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JComboBox<String> isSuperadminComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables

    private static class StopProcessException extends Exception{}
    private static class NullFieldException extends Exception{}

    private static class CurrentAdminUsernameExcpetion extends Exception{}
}
